#pragma once

typedef enum {
    EFFECT_WaterBombHit,
    EFFECT_Ball,
    EFFECT_BallDrop,
    EFFECT_BeachBall,
    EFFECT_Bottle,
    EFFECT_BoxSlide,
    EFFECT_Clockwork,
    EFFECT_Countdown,
    EFFECT_Electro,
    EFFECT_ElectroZap,
    EFFECT_FireworkBang,
    EFFECT_FireworkFire,
    EFFECT_Fuse,
    EFFECT_Hit1,
    EFFECT_Hit2,
    EFFECT_Honka,
    EFFECT_HonkGood,
    EFFECT_LightFlk,
    EFFECT_MenuLeftRight,
    EFFECT_MenuNext,
    EFFECT_MenuPrev,
    EFFECT_MenuUpDown,
    EFFECT_Motor,
    EFFECT_OilDrop,
    EFFECT_Petrol,
    EFFECT_PickupGen,
    EFFECT_Pickup,
    EFFECT_PuttyBombBang,
    EFFECT_Scrape,
    EFFECT_Servo,
    EFFECT_Shock,
    EFFECT_ShockFire,
    EFFECT_SkidNormal,
    EFFECT_SkidRough,
    EFFECT_Splash,
    EFFECT_StarFire,
    EFFECT_Turbo,
    EFFECT_TVStatic,
    EFFECT_UFO,
    EFFECT_WaterBomb,
    EFFECT_WaterBombBounce,
    EFFECT_WaterBombFire,
} sounds_common_EFFECT;
